print("\t Resume:")
print("Name:Zehra Surname:Mammadzada Age:16 Hobby:Shooting")
print("   ---   ")
print("  /    \ ")
print(" /      \ ")
print(" |      |")
print(" |      |")
print(" |      |")
print(" \      /")
print("  \    /")
print("   ---")
print('"To be')
print('        or not')
print('                to be!"')
print('                        /Shakespeare/')
print("    Escape sequences")
print("\\a\tBell (alert)")
print("\\b\tBackspace")
print("\\n\tNew line")
print("\\r\t Carriage return")
print("\\t\tHorizonral tab")
print("\\\\ \t Backslash \\")
print("\\\"   Double quotation mark \"")
print("\\\'   Single quotation mark \'")
print(" ********  *********  *        *  *********             *")
print("       *   *          *        *  *       *           *   *")
print("      *    *          *        *  *       *          *     *")
print("     *     *********  **********  *********         *********")
print("    *      *          *        *  *        *       *         *")
print("   *       *          *        *  *         *     *           *")
print("  *        *          *        *  *          *   *             *")
print(" ********  *********  *        *  *           * *               *")
print("\" \'\\t', \'\\n', '\\\\', '\\'', '\\\"\'\"")
print("       ********************")
print("      *|                 **")
print("     * |                * *")
print("    *  |               *  *")
print("   *   |              *   *")
print("  *    |             *    *")
print(" *     |            *     *")
print("********************      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |           *      *")
print("*      |___________*______*")
print("*     /            *     *")
print("*    /             *    *")
print("*   /              *   *")
print("*  /               *  *")
print("* /                * *")
print("*/                 **")
print("********************")

x = 10 
y= 20
k = x
x = y
y = k
print("x:" ,x)
print("y:" ,y)
x, y = y, x
Name = bool(input("Adinizi daxil edin"))
Surname = input("Soyadinizi daxil edin")
Age = int (input("Yasinizi daxil edin"))
Score = float(input("Xalinizi daxil edin"))

ticket = float(input("Bilet qiymetini daxil edin"))
ticket = float(input(""))
boyukler = int(input("Boyuklerin sayini daxil edin"))
kicikler = int(input("Kiciklerin sayini daxil edin"))
qiymet = 2 + 5
print("Umumi mebleg", qiymet)

