file = open("Example.txt", "w")
file.write("Hakuna Matata\n")
file.close()
file = open("example.txt", "r")
content = file.read()
print(content)
file.close()
file = open("example.txt", "a")
file.write("\nNew Line Added.")
file.close()
file = open("example.txt","w+")
file.write("Overwritten content")
